version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"    
  api:
    container_name: jucr-container
    image: node:14
    restart: always
    working_dir: /usr/src/jucr
    command: bash -c "npm install --only=prod && npm run start:prod"
    environment:
      - API_KEY=ff82541f-c8d1-4507-be67-bd07e3259c4e
    volumes:
      - ./dist/:/usr/src/jucr/dist/
      - ./package.json:/usr/src/jucr/package.json
    ports:
      - "3000:3000"
    links:
      - "mongo"